# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : libshumate
version    : 1.6.0
release    : 20
source     :
    - https://download.gnome.org/sources/libshumate/1.6/libshumate-1.6.0.tar.xz : 66097ee05c3cc4dfbdc124dfc9b885085f5c6ba2f1b2e642d0475987f9222939
homepage   : https://gitlab.gnome.org/GNOME/libshumate
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Shumate is a GTK toolkit providing widgets for embedded maps.
description: |
    Shumate is a GTK toolkit providing widgets for embedded maps.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gtk4)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libprotobuf-c)
    - pkgconfig(libsoup-3.0)
    - pkgconfig(sqlite3)
    - pkgconfig(sysprof-capture-4)
    - gperf
    - vala
setup      : |
    %meson_configure -Dgtk_doc=false
build      : |
    %ninja_build
install    : |
    %ninja_install
