# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : gnome-pomodoro
version    : '1.0'
release    : 23
source     :
    - https://github.com/gnome-pomodoro/gnome-pomodoro/archive/refs/tags/1.0.tar.gz : 1d8d6adcb83d74ae5c05a9caa988bf5dd0c2876af83d3df3588d27f2ee5cf9ab
homepage   : https://gnomepomodoro.org/
license    : GPL-3.0-or-later
component  : office
summary    : A Pomodoro timer for GNOME
description: |
    GNOME Pomodoro is a small application that helps managing time according to Pomodoro Technique. It intends to improve productivity and focus by taking short breaks
builddeps  :
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gom-1.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libadwaita-1)
    - pkgconfig(libcanberra)
    - pkgconfig(libpeas-2)
    - pkgconfig(sqlite3)
    - desktop-file-utils
    - gnome-common
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license COPYING
